# Student Grade Analyzer- NumPy Project

In [1]:
import numpy as np

In [5]:
marks=np.random.randint(13,100,size=50)
marks

array([67, 56, 18, 57, 67, 59, 40, 74, 84, 73, 95, 98, 45, 29, 25, 54, 52,
       75, 71, 35, 30, 79, 53, 65, 36, 50, 84, 52, 86, 92, 96, 98, 88, 60,
       83, 44, 19, 32, 30, 89, 86, 79, 90, 73, 39, 74, 24, 65, 72, 55])

#### Basics Statistics 

In [6]:
mean_score=np.mean(marks)
median_score=np.median(marks)
highest_score=np.max(marks)
lowest_score=np.min(marks)
std_dev_score=np.std(marks)


#### Find Distinction Students

In [8]:
## Failed students first
failed=marks[marks<40]
print(f"Failed students:{failed}")

Failed students:[18 29 25 35 30 36 19 32 30 39 24]


In [9]:
### Students scoring above 85
top_scorers=marks[marks>85]
print(f"Top scorers:{top_scorers}")

Top scorers:[95 98 86 92 96 98 88 89 86 90]


#### Normalize Scores

In [10]:
normalized_scores = (marks - np.min(marks)) / (np.max(marks) - np.min(marks))

print("Normalized Scores:")
print(normalized_scores)

Normalized Scores:
[0.6125 0.475  0.     0.4875 0.6125 0.5125 0.275  0.7    0.825  0.6875
 0.9625 1.     0.3375 0.1375 0.0875 0.45   0.425  0.7125 0.6625 0.2125
 0.15   0.7625 0.4375 0.5875 0.225  0.4    0.825  0.425  0.85   0.925
 0.975  1.     0.875  0.525  0.8125 0.325  0.0125 0.175  0.15   0.8875
 0.85   0.7625 0.9    0.6875 0.2625 0.7    0.075  0.5875 0.675  0.4625]


#### Reshaping the array


In [11]:
reshaped_marks = marks.reshape(5, 10)

print(reshaped_marks)

[[67 56 18 57 67 59 40 74 84 73]
 [95 98 45 29 25 54 52 75 71 35]
 [30 79 53 65 36 50 84 52 86 92]
 [96 98 88 60 83 44 19 32 30 89]
 [86 79 90 73 39 74 24 65 72 55]]


#### Row-wise Average

In [12]:
subject_averages = np.mean(reshaped_marks, axis=1)

print("Subject-wise Averages:")
print(subject_averages)

Subject-wise Averages:
[59.5 57.9 62.7 63.9 65.7]


#### Percentiles

In [13]:
p25 = np.percentile(marks, 25)
p50 = np.percentile(marks, 50)
p90 = np.percentile(marks, 90)

print("25th Percentile:", p25)
print("50th Percentile:", p50)
print("90th Percentile:", p90)

25th Percentile: 44.25
50th Percentile: 65.0
90th Percentile: 90.2


#### Bonus Challenge

In [14]:
theory = np.random.randint(0, 100, 50)
practical = np.random.randint(0, 100, 50)

final_scores = (0.4 * theory) + (0.6 * practical)

print("Theory Scores:")
print(theory)

print("Practical Scores:")
print(practical)

print("Weighted Final Scores:")
print(final_scores)

Theory Scores:
[80 58  1 87 86 52 68 80 67 57 40 52 59 64 15 58 55 23  0 15 45  0 27 37
 11 97 44 90 63  9 64  5 98 54 74 60 46 49 83 83 60  3 44 65 49 24 83 21
 19 65]
Practical Scores:
[90 68 15 13 36 80 26 37 46  0 29  0 35  2 57 93 17 59 43 85 30 88 90 42
 39 56 46 29 95 78 89 55 36 70 35 88 59  9 25 37 75 57  9 65 24 43 62 85
 92 63]
Weighted Final Scores:
[86.  64.   9.4 42.6 56.  68.8 42.8 54.2 54.4 22.8 33.4 20.8 44.6 26.8
 40.2 79.  32.2 44.6 25.8 57.  36.  52.8 64.8 40.  27.8 72.4 45.2 53.4
 82.2 50.4 79.  35.  60.8 63.6 50.6 76.8 53.8 25.  48.2 55.4 69.  35.4
 23.  65.  34.  35.4 70.4 59.4 62.8 63.8]
